---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes
git_repos: yes
lg_setup: yes

dotfiles_repo: https://github.com/djogss/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/workspaces/tools/gitlibs/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc
  - .tmux.conf
  - .bashrc
  - .bash_aliases
  - .gitconfig

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - git
  - gpg
  - iperf
  - mcrypt
  - nmap
  - node
  - nvm
  - ssh-copy-id
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - tmux
  - z
  - jq
  - htop-osx
  - node@8
  - npm
  - peco # filtering https://github.com/peco/peco
  - python3
  - tree
  - zsh
  - zsh-completions
  # LG specific
  - redis
  - gradle
  - autossh

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - caskroom/versions
  - caskroom/cask
  - dteoh/sqa
  - sanemat/font

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - dropbox
  - firefox
  - google-chrome
  - macvim
  - slack
  - transmit
  - visual-studio-code
  - iterm2
  - java8
  - openssl
  - the-unarchiver
  # OSX software
  - spectacle
  - teamviewer
  - grammarly
  - virtualbox
  - virtualbox-extension-pack
  - vlc
  - xmind
  - spotify
  - intellij-idea # community edition


# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
  #  - { name: Keynote, id: 409183694 }
  # - { name: "Tomato One", id: 907364780 }
  #- { id: 784801555, name: "Microsoft OneNote" }
mas_email: "{{ mas_email }}"
mas_password: "{{ mas_password }}"

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages:
  - { name: "@angular/cli" }
  - { name: gulp }
  - { name: karma }
  - { name: typescript }
  - { name: typings }
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages:
  - name: mkdocs
    state: present # present/absent/latest, default: present
  - name: boto
    state: present
  - name: pyyaml
    state: present
  - name: netaddr
    state: present
  - name: docker
    state: present

# LG dev setup
lg_repos:
  - { name: server, repo: "{{ lg_git_repo_domain }}/diffusion/S/server.git" }
  - { name: micro-services, repo: "{{ lg_git_repo_domain }}/diffusion/APMS/micro-services.git" }
  - { name: microservices-libraries, repo: "{{ lg_git_repo_domain }}/diffusion/MSL/microservices-libraries.git" }

# Glob pattern to unusable task files to run after all other tasks are finished.
post_provision_tasks: []

visual_studio_code_extensions:
  - extensionName: autoimport
    publisher: steoates
