---
- name: Ensure configured LG git repos are present.
  git:
    repo: "ssh://git@{{ item.repo }}"
    dest: "$HOME/workspaces/java/lg/{{ item.name }}"
  with_items: "{{ lg_repos }}"
  tags:
    - lg-git-repos
    - lg

- name: Ensures $HOME/.aws dir exists
  file: path=$HOME/.aws state=directory
  tags:
    - lg

- name: Set up aws credentials
  template:
    src: ../templates/lg/aws.credentials.j2
    dest: $HOME/.aws/credentials
  tags:
    - lg

- name: Ensures $HOME/.gradle dir exists
  file: path=$HOME/.gradle state=directory
  tags:
    - lg

- name: Set up nexus credentials in gradle file
  template:
    src: ../templates/lg/gradle.properties.j2
    dest: $HOME/.gradle/gradle.properties
  tags:
    - lg


- name: Log into private registry and force re-authorization
  docker_login:
    registry: "{{ repo }}"
    username: "{{ nexusUser }}"
    password: "{{ nexusUserPass }}"
    reauthorize: yes
  tags:
    - lg
    - foo

- name: pull an lg-postgres
  docker_image:
    name: nexus.live.logicalglue.net/lg-postgres:1
  tags:
    - lg
    - foo

- name: Create a lg-postgres container
  docker_container:
    name: lg-postgres-db
    image: "{{ repo }}/lg-postgres:1"
    ports: "15432:5432"
  tags:
    - lg
    - foo


# manual installation is required
#- name: Install arc certificates
#  command: arc install-certificate arg1
#  args:
#    chdir: $HOME/workspaces/java/lg/server
#  tags: lg
